name: BlockEntities
version: 1.1.0
main: im.dnn.BlockEntities.BlockEntities
api-version: 1.19
depend: [Residence]
commands:
  blockentities:
    description: BlockEntities base command
    usage: /blockentities help

permissions:
  blockentities.reload:
    description: Allows to execute the reload command
    default: false
  blockentities.get:
    description: Allows to use the get command to the players
    default: false